{
  "backend": {
    "repo": "rem95/Art-Lamps", 
    "name": "github", 
    "branch": "main", 
    "base_url": "https://rem95.github.io/Art-Lamps"
  }, 
  "public_folder": "/images/uploads", 
  "collections": [
    {
      "slug": "{{year}}-{{month}}-{{day}}-{{slug}}", 
      "name": "blog", 
      "fields": [
        {
          "widget": "string", 
          "name": "title", 
          "tagname": "h2", 
          "label": "Title"
        }, 
        {
          "widget": "datetime", 
          "name": "date", 
          "label": "Publish Date"
        }, 
        {
          "widget": "image", 
          "required": false, 
          "name": "image", 
          "label": "Featured Image"
        }, 
        {
          "widget": "markdown", 
          "name": "body", 
          "label": "Body"
        }
      ], 
      "create": true, 
      "folder": "_posts", 
      "label": "Religious Blog"
    }
  ], 
  "media_folder": "images/uploads"
}